version : '3.1'
services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    env_file:
      .env
    volumes:
      - "./database/scripts:/docker-entrypoint-initdb.d"
    healthcheck:
      test: "ls /var/run/mysqld/mysqld.sock && exit 0"
  my-app:
    image: node:14
    working_dir: /app
    entrypoint: bash -c 'npm install && node index.js'
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - "./app:/app"
    depends_on:
      mysql:
        condition: service_healthy