version : '3.1'
services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    env_file:
      .env
    volumes:
      - "./database/scripts:/docker-entrypoint-initdb.d"
    healthcheck:
      test: "ls /var/run/mysqld/mysqld.sock && exit 0"
      interval: 1s
  my-app:
    build:
      context: app
    working_dir: /app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s bash -c 'npm install && node index.js'
    env_file:
      - .env
    volumes:
      - "./app:/app"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  web:
    build:
      context: nginx
    entrypoint:  dockerize -wait tcp://my-app:3000 -timeout 30s /conf/docker-entrypoint.sh
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - my-app